version: '3'

services:
  db:
    restart: always
    image: postgres:14.0
    environment:
      - POSTGRES_USER=django_chatGPTUser
      - POSTGRES_PASSWORD=django_chatGPTPassword
    volumes:
      - "django_chatGPT_db_data:/var/lib/postgresql/data"
    expose:
      - 5432
    ports:
      - 5433:5432
    networks:
      - django_chatGPT_backend_tier

  redis:
    restart: always
    image: redis:latest
    networks:
      - django_chatGPT_backend_tier

  django_chatGPT:
    restart: always
    build: .
    depends_on:
      - redis
      - db
    env_file: .env
    command: gunicorn django_chatGPT.wsgi:application --bind 0.0.0.0:8009 --workers 3 --log-level=DEBUG
    links:
      - db:postgres
      - redis
    ports:
      - "8009:8009"
    expose:
      - "8009"
    volumes:
      - .:/app
    networks:
    - django_chatGPT_backend_tier

  celery:
    build: .
    command: celery -A django_chatGPT worker -l info
    env_file: .env
    restart: unless-stopped
    depends_on:
      - db
      - redis
    networks:
      - django_chatGPT_backend_tier

  nginx:
    build: ./nginx
    depends_on:
      - django_chatGPT
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./static:/app/static/
      - ./media:/app/media/
      - ./logs/Nginx:/var/log/nginx/
    networks:
      - django_chatGPT_backend_tier

volumes:
  django_chatGPT_db_data:
    driver: local
  static_volume:
    driver: local

networks:
  django_chatGPT_backend_tier:
    driver: bridge

